### ISSUE TITLE
Update marmalade-repo with version 1.2

### ISSUE THREAD

**Issue by bostonaholic** [mustache/emacs#4]
@haxney Please upload the newest version of mustache-mode.el to http://marmalade-repo.org/packages/mustache-mode.

Thanks!

**Comment by iainbeeston** [comment]
+1 for this. Nobody else can update it because @haxney is the owner on marmalade

**Comment by wfarr** [comment]
:+1: to this.

**Comment by haxney** [comment]
Can do. I recommend getting mustache-mode on MELPA since Marmalade
development seems to have died.
On Dec 28, 2011 7:47 PM, "Matthew Boston" <
reply@reply.github.com>
wrote:

**Comment by haxney** [comment]
Done. If anyone else has an account on Marmalade, let me know and I can add them as an owner.

**Comment by locks** [comment]
From what I understand after reading the thread, this issue can be closed.
Thank you!
